<?php

namespace Strut\StrutBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Strut\UserBundle\Entity\User;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
    public function getPictures(User $user): QueryBuilder
    {
        return $this->createQueryBuilder('picture')
            ->leftJoin('picture.presentation', 'presentation')
            ->leftJoin('presentation.user', 'u')
            ->where('u.id = :userId')->setParameter('userId', $user->getId())
            ->orderBy('picture.createdAt', 'desc')
        ;
    }
}
